version: '3'

services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=flowreader
      - POSTGRES_USER=flowreader
      - POSTGRES_PASSWORD=flowreader

  web:
    build: .
    command: python /app/src/manage.py runserver
    entrypoint: /app/src/entrypoint.sh
    depends_on:
      - db
    environment:
      - SECRET_KEY=CorrectHorseBatteryStaple
      - DATABASE_URL=postgres://flowreader:flowreader@db:5432/flowreader
    ports:
      - "8000:8000"
