# Generated by Django 3.2 on 2021-05-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mpan",
                    models.CharField(
                        max_length=21, verbose_name="Meter Point Administration Number."
                    ),
                ),
                (
                    "flow_file",
                    models.CharField(
                        max_length=255,
                        verbose_name="Flow file this reading was taken from.",
                    ),
                ),
                (
                    "meter_serial_number",
                    models.TextField(
                        verbose_name="Serial number of the meter this reading was taken from."
                    ),
                ),
            ],
        ),
    ]
